# defining services (only nextjs for now)
services:
  nextjs:
    image: zoryon/next-starter-${ENV}:1.0
    container_name: next-starter
    build: 
      context: ./
      target: 'image-${ENV}'
      args:
        NEXT_PUBLIC_ENVIRONMENT: '${ENV}'
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    environment:
      NEXT_PUBLIC_ENVIRONMENT: '${ENV}'
    env_file:
      - .env